# Generated by Django 4.2.6 on 2023-10-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveler',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
